PrimeFaces.widget.EditorI18NProvider.messageBundle["it"] = {
	MSG_FONT_NAME_AND_SIZE : "Nome e Tipo di Font",
	MSG_FONT_STYLE : "Stile",
	MSG_UNDO_REDO : "Avanti/Indietro",
	MSG_ALIGNMENT : "Allineamento",
	MSG_PARAGRAPH_STYLE : "Stile Paragrafo",
	MSG_INDENTING_AND_LISTS : "Rientro/Liste",
	MSG_INSERT_ITEM : "Link/Immagini",
	STR_IMAGE_BORDER : "Bordi",
	STR_IMAGE_BORDER_SIZE : "Tam",
	STR_IMAGE_COPY : "Copia",
	STR_IMAGE_BORDER_TYPE : "Tipo",
	STR_IMAGE_ORIG_SIZE : "Dimensione",
	STR_IMAGE_PADDING : "Margini",
	STR_IMAGE_PROP_TITLE : "Inserire Immagine",
	STR_IMAGE_SIZE : "Dimensioni",
	STR_IMAGE_TEXTFLOW : "Alleamento",
	STR_IMAGE_TITLE : "Titolo",
	STR_IMAGE_URL : "Img. URL",
	STR_IMAGE_HERE : "",
	STR_LINK_NEW_WINDOW : "Apri in nuova finestra",
	STR_LINK_PROP_REMOVE : "Rimuovi Link",
	STR_LINK_PROP_TITLE : "Inserisci Link",
	STR_LINK_TITLE : "Titolo",
	STR_LOCAL_FILE_WARNING : "Attenzione",
	STR_NONE : "nessuno"
};